version: 2
jobs:
  build:
    working_directory: /home/circleci/my-company
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout

      - restore_cache:
          key: my-company-angular-fe2-{{ checksum "package.json" }}

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          key: my-company-angular-fe2-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - /home/circleci/my-company/node_modules

      - run:
          name: angular-test
          command: yarn test -- --single-run --no-progress

      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - run:
          name: angular-build-stage
          command: |
            mkdir stage
            rm -rf dist stage
            yarn ng build --stage
            cp -R dist/* stage/
            touch stage/Staticfile

      - run:
          name: angular-build-prod
          command: |
            mkdir prod
            rm -rf dist prod
            yarn ng build --prod
            cp -R dist/* prod/
            touch prod/Staticfile


      - persist_to_workspace:
              root: /home/circleci/my-company/
              paths:
                - stage/
                - prod/

  staging:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - attach_workspace:
          at: workspace/
      - run:
          name: Install CloudFoundry CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
      - deploy:
          name: Deploy to Staging - PWS CLoudFoundry (CF_PASSWORD variable required)
          command: |
            cf api https://api.run.pivotal.io
            cf auth idugalic@gmail.com $CF_PASSWORD
            cf target -o idugalic -s Stage
            cd workspace/stage
            cf push stage-my-company-angular-fe --no-start
            cf start stage-my-company-angular-fe

notify:
  webhooks:
  # A list of hashes representing hooks. Only the url field is supported.
    - url: https://webhook.atomist.com/atomist/circle

workflows:
  version: 2
  my-company-angular-fe-workflow:
    jobs:
       - build
           context: org-global
       - staging:
           context: org-global
           requires:
             - build
           filters:
             branches:
               only: master
